version: '3.7'

services:
  service:
    container_name: verbose
    build: .
    restart: always
    labels:
      caddy: verbose.raphaelpour.de
      caddy.reverse_proxy: "{{upstreams http 8000}}"
    volumes:
      - data:/usr/lib/verbose/

volumes:
  data:

networks:
  default:
    external:
      name: aproxymate_caddy
